filme/urls.py
from django.urls import path,reverse_lazy
from .views import Homepage, Homefilmes, Detalhesfilme, Pesquisafilme, Pagperfil, Criarconta
# homepage, homefilmes
# o nome tem q ser diferente pois já há outro views(.views) - AULA (36)
from django.contrib.auth import views as auth_view

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    # int:pk pqnã é para todos os filmes
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editperfil/<int:pk>', Pagperfil.as_view(), name='editperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    # template_name='editperfil.html' para reaproveitar, se quise-se outras funcionabilidades, teria que criar outra
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(
        template_name='editperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),

]


# path('', homepage) - se fosse utiliza minha de em vez da class,
# path('filmes/', homefilmes),

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace="filme")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #para as imgs do django

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
import PIL


# ('armazena_no_banco', 'aparece_pro_user')
LISTA_CATEGORIAS = (
    ("Analises", "Análises"),
    ("Programacao", "Programação"),
    ("Apresentacao", "Apresentação"),
    ("Outros", "Outros"),
)


# Filme
class Filme(models.Model):
    title = models.CharField(max_length=100)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    thumb = models.ImageField(upload_to='thumb_filmes')
    # Text É um bloco para escrever
    descricao = models.TextField(max_length=1000)
    qtd_views = models.IntegerField(default=0)
    date_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title


class Episodio(models.Model):
    # um pra muitos ('Nome da tabela', related_name='', on_delete=models.CASCADE) ---- se for muitos para muitos é models.ManyToManyField
    filme = models.ForeignKey(
        'Filme', related_name='episodios', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self) -> str:
        return self.filme.title + " - " + self.title


class User(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme") #muitos users podem ver vários fil. ou um user pode ver vários fil.

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

# O forms precisa ser importado no VIEWS (CriarContaForm) e o FormView
# Sub classe da classe UserCreationForm

# AULA (40)


class CriarContaForm(UserCreationForm):
    email = forms.EmailField(required=True)

    # Necessário para dizer qual modelo deve-se USAR COMO REFERÊNCIA/BASE
    class Meta:
        model = User
        # senha e confirmação de senha
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Este e-mail já está cadastrado em outra conta! Por favor, utilize outro endereço de e-mail.")
        return email

# A função "clean_email()" checa no banco de dados se o e-mail já existe na tabela de usuários.
# Em caso de existir, retorna a mensagem e bloqueia a criação da conta; inversamente, se o e-mail não existe, a conta é criada.


# Form padrão do Django
class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)

filme/views.py
from typing import Any
from django import http
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, reverse
from .models import Filme, User
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# ulr - view - html

#   Function base views -VS- Class base views   #

# def homepage(request):
# return render(request, 'homepage.html')

# A mesma coisa do de cima, só que ele já tem a função de get e de post


class Homepage(FormView):
    template_name = 'homepage.html'
    form_class = FormHomepage

    # AULA (37)
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        if request.user.is_authenticated:  # usuario está autenticado
            return redirect('filme:homefilmes')  # redireciona para a home
        else:
            # tem super pq estamos editando, neste caso, função que já existe
            return super().get(request, *args, **kwargs)

# Verificar e redirecionar o user para criar conta
    def get_success_url(self):
        email = self.request.POST.get("email")
        user = User.objects.filter(email=email)
        if user:
            return reverse('filme:login')
        else:
            return reverse('filme:criarconta')


# def homefilmes(request):
    # x- aula 20 -11:20 ou 07:00
    # x-  context = {}
    # x- context['lista_filmes'] = lista_filmes

    # lista_filmes = Filme.objects.all()

    # return render(request, 'homefilmes.html', {'lista_filmes': lista_filmes}) #context

# listview pois é uma lista e LoginRequiredMixin é só pra conseguir acessar a pag se tiver feito login
class Homefilmes(LoginRequiredMixin, ListView):
    template_name = 'homefilmes.html'
    model = Filme  # ele já faz tudo q faz em cima automaticamente // model vira um object_list


class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = 'detalhes.html'
    model = Filme  # object -> 1 item do nosso modelo

    # aula (28)
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        # descobrir qual o filme ele tá acessando
        filme = self.get_object()
        filme.qtd_views += 1
        # soma 1 nas visualizacoes e salvar
        filme.save()
        user = request.user
        # Não é .append pis é para adicionar no banco de dados e não uma lista no python, ADD, ASSIM COMO O FILTER E ETC, SÃO MÉTODOS PAR BANCO DE DADOS
        user.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs)  # Redireciona o user para url final

    # Filmes relacionados #Aula (26)
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super(Detalhesfilme, self).get_context_data(**kwargs)
        # Preciso pegar o object, então é usado get_object()
        filmes_relacionados = Filme.objects.filter(
            categoria=self.get_object().categoria)[0:5]  # Só pega/limita 5 filmes relacionados
        context["filmes_relacionados"] = filmes_relacionados
        return context


class Pesquisafilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    # Edita o object_list
    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            # self.model aula (32), pois se a model mudar de nome (ex: Filme para Episodio), ele não dá erro
            object_list = self.model.object.filter(
                title__icontains=termo_pesquisa)
            return object_list
        else:
            return None


# LoginreequiredMixin é para só acessar a pagina se estiver logado
class Pagperfil(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "editperfil.html"
    model = User
    fields = ['first_name', 'last_name', 'email']

    def test_func(self):  # user_nao_pode_mudar_perfil_de_outro — importar o UserPassesTestMixin
        user = self.get_object()
        return self.request.user == user

    def get_success_url(self) -> str:
        return reverse('filme:homefilmes')


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

# O FORM É VALIDO?
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# A funcao quer um link, por isso o reverse e não o redirect


    def get_success_url(self) -> str:
        return reverse('filme:login')

filme/templates/detalhes.html
{% extends 'base.html' %}

{% block title %}
HomeFilmes HashFlix
{% endblock %}

{% block 'body' %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ object.title }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":100" }}...
            </p>
            <div class="flex my-4">
                <a href="{{ object.episodios.first.video }}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.qtd_views }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios

                </h2>
                {% for episodio in object.episodios.all %}
                    <h3 class='text-lg'>
                        <a href="{{ episodio.video }}">  <!-- video já é um link -->
                            <p>Episódio {{ forloop.conter }}: {{ episodio.title }}</p>
                        </a>
                    </h3>
                {% endfor %}

            </div>

        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filmes in filmes_relacionados %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}">  <!-- vai direcionar para o video especifico -->
                            <img src="filme.thumb.url " class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    
</main>

{% endblock %}

filme/templates/editperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Editar Perfil
{% endblock %}

{# AULA (42) #}
{% block 'body' %}
   {#Editperfil precisa agora de uma Key, isso é feio pelo Nav#}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'img/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">{{ user.username }}</h2> {#pode ser identificado pelo email#}

        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
        </form>
        <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>

{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomeFilmes HashFlix
{% endblock %}

{% block head %}
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;
    
    .item {
      padding: 0 2px;
      transition: $duration all;
      
      &:hover { 
        margin: 0 40px;
        transform: scale(1.2);
      }
      
    }
    
    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;
      
      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      
    }
    
  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>
{% endblock %}


{% block 'body' %}

  <main class='bg-primary_black min-h-screen w-full'>
      <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');">
          <div>
              <h2 class="text-6xl font-semibold text-white my-4">
              {{ filme_destaque.title }}
              </h2>
              <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                  {{ filme_destaque.descricao }}
              </p>
              <div class="flex my-4">
                  <a href="{% url 'filme:detalhesfilme' filme_destaque.pk %}">
                      <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                          <ion-icon name="play" class="text-2xl"></ion-icon>
                          <span class="ml-3 font-medium " >
                              Play
                          </span>
                      </button>
                  </a>
              </div>
          </div>
      </section> 


    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Novo
            </h2>
            <div class="wrapper">
              <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                {% for filme in list_filmes_recentes %}
                {% if forloop.counter < 5 %} {#Se o contador do for, ser menor que 5, exibe o filme #}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                  {% endif %}
                  {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
              </section>
              {% if list_filmes_recentes|length > 4 %}
                  <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                    {% for filme in list_filmes_recentes %}
                    {% if forloop.counter > 4 %} {#Se o contador do for, for a partir de 5, exibe o filme #}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% endif %}
            </div>


        </div>
    </section>




    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Em Alta
            </h2>
            <div class="wrapper">
              <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                {% for filme in list_filmes_em_alta %}
                {% if forloop.counter < 5 %} {#Se o contador do for, ser menor que 5, exibe o filme #}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                  {% endif %}
                  {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
              </section>
              {% if list_filmes_em_alta|length > 4 %}
                  <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                    {% for filme in list_filmes_em_alta %}
                    {% if forloop.counter > 4 %} {#Se o contador do for, for a partir de 5, exibe o filme #}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                    <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% endif %}
            </div>


        </div>
    </section>
  



    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Continuar Assistindo
            </h2>
            <div class="wrapper">
              <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
                {% for filme in request.user.filmes_vistos.all %}
                {% if forloop.counter < 5 %} {#Se o contador do for, ser menor que 5, exibe o filme #}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                  {% endif %}
                  {% endfor %}
                    <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
              </section>
              {% if request.user.filmes_vistos.all|length > 4 %}
                  <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                    {% for filme in request.user.filmes_vistos.all %}
                    {% if forloop.counter > 4 %} {#Se o contador do for, for a partir de 5, exibe o filme #}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                      {% endif %}
                      {% endfor %}
                    <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                  </section>
                  {% endif %}
            </div>


        </div>
    </section>



</main>


{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
HomePage HashFlix
{% endblock %}

{% block head %}
<style> {# coloca a fonte preta na barra de Acessar #}
    #id_email{
        width: 100%;
        color: #000000;
        padding: 5px 5px;
    }
</style>
{% endblock %}

{#5px 5 px - É a distância do texto, para n ficar colado com o input#}


{% block 'body' %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-cover bg-center" style="background-image: url('{% static 'img/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex flex-col items-center">
        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4">
            Filmes e séries da Hashtag, tudo em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>
        <div class="w-full flex justify-center">
            <div class="w-full max-w-lg">
                <form method="post" class="flex flex-col items-center">
                    {% csrf_token %}
                    <div class="flex w-full max-w-lg">
                        <input id="id_email" type="email" name="email" placeholder="Digite seu e-mail" 
                        class="flex-grow py-2 px-4 rounded-l-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-red-600" style="max-width: 500px;">
                        <button class="bg-red-600 text-white font-medium py-2 px-4 rounded-r-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-600" 
                        type="submit" style="width: 120px;">
                            <span>Acessar</span>
                            <ion-icon name="chevron-forward-outline" class="text-xl ml-2"></ion-icon>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Enjoy on your TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'img/tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'img/mobile-0819.jpg' %}" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md:text-xl text-lg">
            Save your favorites easily and always have something to watch.
        </h5>
    </div>
    
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create profiles for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'img/netflix_kid.png' %}" class="w-8/12" alt="">
    </div>
</section>
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2023</li>
        <li>Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>


{% endblock %}

filme/templates/pesquisa.html
{% extends "base.html" %}

{% block title %}
Pesquisa de Filmes
{% endblock  %}

{% block 'body' %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Resultados da Busca
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
              {% for filme in object_list %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                      <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
              {% endfor %}
            </div>


        </div>
    </section>
</main>




{% endblock  %}

templates/navbar.html
{% load static %}


<nav class="w-full flex justify-between items-center py-2 px-3 fixed z-50">
    <div class="w-6/12"> <!--divido em 6 para os dois, sendo que no total o espaço é 12-->
        <!-- rounded-md deixa as pontas redondas -->
        <a href='/'> <!-- joga sempre para pag inicial apos clicar na logo poe exem-->
            <img class="w-2/12" src="{% static 'img/hashflix.png' %}">
        </a>
    </div>

  
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2"> <!-- margem right // flex é para colocar um do lado do outro e flex-nowrap para ele não ajustar  -->
            <form method="get" action="{% url 'filme:pesquisafilme' %}"> {# Pesquisar não é post (mas dá pra fazer com post), ele apenas redireciona #}
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">
                <input type="submit" value="">
            </form>
        </div>
        {% endif %}

        <div class="mr-2">
        {% if user.is_authenticated %}
            <a href="{% url 'filme:logout' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Sair</button>
                <!-- py é a distância da letra -->
            </a>
        {% else %}
            <a href="{% url 'filme:login' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Login</button>
                <!-- py é a distância da letra -->
            </a>
            {% endif %}
        </div>

        {% if user.is_authenticated %}
        <div class="mr-2 flex flex-nowrap justify-end">
            <a href="{% url 'filme:editperfil' request.user.id %}"> <!-- Criar a view, a url para redirecionar e o template pelo id/pk autenticado -->
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">Editar Perfil</button>
            </a>
        </div>
        {% endif %}

    </div>
   
</nav>